#!/bin/sh
set -eu

self="$0"
while [ -L "$self" ]; do
  target=$(readlink "$self")
  case "$target" in
    /*) self="$target" ;;
    *) self="$(dirname "$self")/$target" ;;
  esac
done
root=$(CDPATH= cd -- "$(dirname "$self")/.." && pwd)
PYTHONPATH="$root${PYTHONPATH:+:$PYTHONPATH}" exec python3 -m nexus "$@"
